name: minerva-proj
channels:
    - conda-forge
    - anaconda
    - pytorch
dependencies:
    - python=3.8
    - pandas
    - numpy
    - scikit-learn
    - nltk
    - regex
    - pip
    - nvidia::cudatoolkit=11.7
    - pytorch::pytorch
    - pip:
        - wandb
        - jsonlines
        - langid
        - transformers==4.17
        - torchnet
        - littlebird-twitter-utils
        - fastBPE
        - iso3166
